POST http://localhost:3000/products
content-type: application/json

{
    "product_name": "Chocolate Chip Cookies",
    "category": "Snack",
    "price": 5.49,
    "ingredients": "Flour,Sugar,Butter,Chocolate Chips,Eggs",
    "productionDate": "2025-04-05",
    "expirationDate": "2025-09-05"
}


###
POST http://localhost:3000/products
content-type: application/json

{
    "product_name": "Peanut Butter Energy Bars",
    "category": "Snack",
    "price": 2.99,
    "ingredients": "Oats,Peanut Butter,Honey,Chia Seeds,Cocoa Powder",
    "productionDate": "2025-04-03",
    "expirationDate": "2025-07-03"
}


###
POST http://localhost:3000/products
content-type: application/json

{
    "product_name": "Cheddar Cheese Crackers",
    "category": "Snack",
    "price": 3.99,
    "ingredients": "Wheat Flour,Cheddar,Cheese,Butter,Salt,Paprika",
    "productionDate": "2025-03-20",
    "expirationDate": "2025-08-20"
}

### 
GET http://localhost:3000/products/1

###
GET http://localhost:3000/Bakery_Products/1

###
GET http://localhost:3000/products/3