POST http://localhost:3000/products
content-type: application/json

{

}

###
POST http://localhost:3000/products
content-type: application/json

{

}

###
POST http://localhost:3000/products
content-type: application/json

{

}

### 
GET http://localhost:3000/products
content-type: application/json

{

}

###
GET http://localhost:3000/products
content-type: application/json

{

}

###
GET http://localhost:3000/products
content-type: application/json

{

}
