POST http://localhost:3000/products
content-type: application/json

{
    "product_name": "Chocolate Chip Cookies",
    "category": "Snack",
    "price": 5.49,
    "ingredients": "Flour,Sugar,Butter,Chocolate Chips,Eggs",
    "quantity": 34,
    "productionDate": "2025-04-05",
    "expirationDate": "2025-09-05"
}


###
POST http://localhost:3000/products
content-type: application/json

{
    "product_name": "Peanut Butter Energy Bars",
    "category": "Snack",
    "price": 2.99,
    "ingredients": "Oats,Peanut Butter,Honey,Chia Seeds,Cocoa Powder",
    "quantity": 4,
    "productionDate": "2025-04-03",
    "expirationDate": "2025-07-03"
}


###
POST http://localhost:3000/products
content-type: application/json

{
    "product_name": "Cheddar Cheese Crackers",
    "category": "Snack",
    "price": 3.99,
    "ingredients": "Wheat Flour,Cheddar,Cheese,Butter,Salt,Paprika",
    "quantity": 5,
    "productionDate": "2025-03-20",
    "expirationDate": "2025-08-20"
}

### 
GET http://localhost:3000/products/1

###
GET http://localhost:3000/products/2

###
GET http://localhost:3000/products/3

###
DELETE http://localhost:3000/products/delete-product?deleteType=id&deleteQuery=30

###
DELETE http://localhost:3000/products/delete-product?deleteType=id&deleteQuery=40

###
DELETE http://localhost:3000/products/delete-product?deleteType=id&deleteQuery=50

###
DELETE http://localhost:3000/products/delete-product?deleteType=name&deleteQuery=

###
DELETE http://localhost:3000/products/delete-product?deleteType=name&deleteQuery=

###
DELETE http://localhost:3000/products/delete-product?deleteType=name&deleteQuery=

# for test connexion with good values result= 200 OK
###
POST http://localhost:3000/products/login
content-type: application/json

{
    "username": "admin",
    "password": "1234"
}

#for test connexion with wrong values result= 401 Unauthorized
###
POST http://localhost:3000/products/login
content-type: application/json

{
    "username": "admin",
    "password": "0000"
}

#for feedback form test